name: Docker Image Publish

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Checkout code first

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v2 # Action to log into ACR
        with:
          # Corrected: Login server for your glgacr registry
          login-server: glgacr.azurecr.io
          # Corrected: Use the secrets you created
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build, tag, and push image to Azure Container Registry
        run: | # Use multi-line run script for clarity
          # Build using WebApp.Dockerfile, tag with date/run number and 'latest'
          docker build . --file WebApp.Dockerfile --tag glgacr.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_${{ github.run_number }}
          docker tag glgacr.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_${{ github.run_number }} glgacr.azurecr.io/sample-app-aoai-chatgpt:latest
          # Push both the specific tag and the 'latest' tag
          docker push glgacr.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_${{ github.run_number }}
          docker push glgacr.azurecr.io/sample-app-aoai-chatgpt:latest
