# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - PB25

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://glgaicontainerregistry/
        username: ${{ secrets.AzureAppService_ContainerUsername_9859fe78eded47f2b86ee32be53b1bdd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_61b1d6b088a942bba3cd39f1c9a4befa }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: glgaicontainerregistry/${{ secrets.AzureAppService_ContainerUsername_9859fe78eded47f2b86ee32be53b1bdd }}/joogni-chatbot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'PB25'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ff4850b2abf4480397dd8fef471fd9dd }}
        images: 'glgaicontainerregistry/${{ secrets.AzureAppService_ContainerUsername_9859fe78eded47f2b86ee32be53b1bdd }}/joogni-chatbot:${{ github.sha }}'